### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by DavisYao88** [electron/chromedriver#51] opened 2019-11-26 03:33 UTC
```
electron-chromedriver@3.0.0 install 
/node_modules/electron-chromedriver
 node ./download-chromedriver.js

/node_modules/electron-chromedriver/download-chromedriver.js:19
  if (err != null) throw err
                   ^
Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@3.0.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in
```

**Comment by easonwanger** [comment] 2020-01-07 15:33
Try to use mirror ELECTRON_MIRROR=https://cdn.npm.taobao.org/dist/electron/

**Comment by alex-dow** [comment] 2020-02-19 19:38
Unfortunately this does not work for me.

The logs are tricky to figure out but if you run in verbose mode, I get 404 errors

```
[INFO] verbose 9.547002537 (node:19414) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
[INFO]     at EventEmitter.<anonymous> (/home/adowgail/workspace.apps/mtm-studio4/node_modules/got/source/as-stream.js:35:24)
[INFO]     at EventEmitter.emit (events.js:223:5)
[INFO]     at module.exports (/home/adowgail/workspace.apps/mtm-studio4/node_modules/got/source/get-response.js:22:10)
[INFO]     at ClientRequest.handleResponse (/home/adowgail/workspace.apps/mtm-studio4/node_modules/got/source/request-as-event-emitter.js:155:5)
[INFO]     at Object.onceWrapper (events.js:313:26)
[INFO]     at ClientRequest.emit (events.js:228:7)
[INFO]     at ClientRequest.origin.emit (/home/adowgail/workspace.apps/mtm-studio4/node_modules/@szmarczak/http-timer/source/index.js:37:11)
[INFO]     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
[INFO]     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
[INFO]     at TLSSocket.socketOnData (_http_client.js:456:22)
```

Then further down we get

```
[INFO] Error: Failed to find Electron v7.0.0 for linux-x64 at https://username:*****@private-corporate-artifactory.com/electron/7.0.0/chromedriver-v7.0.0-linux-x64.zip
[INFO]     at Request.<anonymous> (/home/adowgail/workspace.apps/mtm-studio4/node_modules/nugget/index.js:169:61)
[INFO]     at Request.emit (events.js:223:5)
[INFO]     at Request.onRequestResponse (/home/adowgail/workspace.apps/mtm-studio4/node_modules/request/request.js:1066:10)
[INFO]     at ClientRequest.emit (events.js:223:5)
[INFO]     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
[INFO]     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
[INFO]     at TLSSocket.socketOnData (_http_client.js:456:22)
[INFO]     at TLSSocket.emit (events.js:223:5)
[INFO]     at addChunk (_stream_readable.js:309:12)
[INFO]     at readableAddChunk (_stream_readable.js:290:11)
[INFO]     at ProcessTermError.ExtendableBuiltin (/home/adowgail/workspace.apps/mtm-studio4/packages/mtm-deployer/node/yarn/dist/lib/cli.js:721:66)
[INFO]     at ProcessTermError.MessageError (/home/adowgail/workspace.apps/mtm-studio4/packages/mtm-deployer/node/yarn/dist/lib/cli.js:750:123)
[INFO]     at new ProcessTermError (/home/adowgail/workspace.apps/mtm-studio4/packages/mtm-deployer/node/yarn/dist/lib/cli.js:790:113)
[INFO]     at ChildProcess.<anonymous> (/home/adowgail/workspace.apps/mtm-studio4/packages/mtm-deployer/node/yarn/dist/lib/cli.js:25884:17)
[INFO]     at ChildProcess.emit (events.js:223:5)
[INFO]     at maybeClose (internal/child_process.js:1021:16)
[INFO]     at Socket.<anonymous> (internal/child_process.js:430:11)
[INFO]     at Socket.emit (events.js:223:5)
[INFO]     at Socket.emit (events.js:223:5)error /home/adowgail/workspace.apps/mtm-studio4/node_modules/electron-chromedriver: Command failed.
[INFO] Exit code: 1
```

Since the URL does indeed work (I can copy it from the log and use it in my browser just fine), it suggests to me that the URL is modified somewhere. IT's also very frustrating that to know the error you need --verbose.

At first I thought maybe the username/password is being removed but removing them still gives me a 404 instead of a 401.

**Comment by alex-dow** [comment] 2020-02-19 19:53
ah, the error message has nothing to do with chromedriver, it's looking for this file: SHASUMS256.txt

guess the issue is really just the logging not telling you what the problem is

**Comment by codebytere** [comment] 2022-05-17 08:09
Closing as this is resolved in recent versions.

**Closed by codebytere** 2022-05-17 08:09 UTC
